### ISSUE TITLE
Breadcrumbs not updating due to React.memo

### ISSUE THREAD

**Issue by nileke** [sebgroup/react-components#35]
**Describe the bug**
We have an issue with Breadcrumbs caused by React.memo. In our container component we have a list of the breadcrumbs which we manipulate (push/pop) in order to update the breadcrumbs. Since memo only does a shallow compare it will think that the props are still the same, it's the same object but different content. 

Our workaround for now is to copy the list every time we update the breadcrumbs to force a rerender. 

If it's by design maybe updating the documentation would be an alternative.

**To Reproduce**
1. Pass list of strings as props to Breadcrumbs component
2. Push or pop new item to list
3. (error) Breadcrumbs unchanged

**Expected behavior**
Breadcrumbs rerender with new list content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7/10
 - Chrome/Firefox
 - Version Chrome/74, Firefox/67 

**Smartphone (please complete the following information):**
N/A

**Additional context**
Issue started after the memo update

**Comment by hjalmers** [comment]
Just stumbled upon this issue and I'm not that familiar with this library or the app you're building @nileke but I'd say that a lot of frameworks and library such as react, angular, vue etc. nowadays expect or prefer states that are immutable, especially if you're following a redux pattern or using a some kind of central store to handle the state. Using push and pop mutates the state so you'd probably want to create a new reference by doing a shallow copy like you're currently doing. Personally I tend to use the "new" spread operator that was introduced with ES6 i.e so instead of doing this:

**The "old" way using push...**
```
const array = [1, 2, 3, 4]
array.push(5);

```

**...use the "new" spread operator and do this**
```
const array = [1, 2, 3, 4]
array = [...array, 5]

```

This could of course be added as part of the library too but generally I'd say you want to avoid push and pop in you're app as they mutate the state.

**Comment by nileke** [comment]
I think why we're having the issue is because this part of the app (where we use Breadcrumbs) is not part of the central state. I think we have to do a more solid workaround and maybe keep this information in our state instead. 

Now that you point it out it feels obvious that we should consider it immutable, as we do with similar variables.

**Comment by yousifalraheem** [comment]
This issue has been tested with the immutable way of changing the state ([mentioned above](https://github.com/sebgroup/react-components/issues/35#issuecomment-512354521)) and it is working as expected
```typescript
const array = [1, 2, 3, 4]
array = [...array, 5]
```
Therefore, this issue is no longer valid
