### ISSUE TITLE
Property 'error' does not exist on type RadioGroupProps

### ISSUE THREAD

**Issue by kherP** [sebgroup/react-components#71]
**Describe the bug**
there is no way to set error message to the radio group as the error props is removed. According to the [documentation ](https://sebgroup.github.io/react-components/#/radiogroup), I should be able to set error message.

**To Reproduce**
1. define `RadioGroup` component
2. set error message
3. see error

**Expected behavior**
Should be able to set error message like other form components

**Comment by yousifalraheem** [comment]
Property error is no longer valid in both Checkboxes and Radio buttons until further notice. The reason is that the radio buttons and checkboxes represents the allowable values and showing that the user has committed an error by choosing one of the allowable values is bad UX.

Note: It might be brought back when developing this feature #54 which will revamp how we handle indicators for multiple states (success, warning, error)
