### ISSUE TITLE
React specified as dependency causes issues with hooks

### ISSUE THREAD

**Issue by nileke** [sebgroup/react-components#82]
**Describe the bug**
React (and react-dom?) is listed as a dependency rather than a peerDependency and devDependency. This causes error on pages rendering a component from react-components which uses hooks with the following error:
```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

```
More info at: https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

`npm ls react` yields

```
λ npm ls react

+-- @sebgroup/react-components@2.0.2
| `-- react@16.10.2
`-- react@16.10.2
```
Which according to the docs is incorrect:

> In order for Hooks to work, the react import from your application code needs to resolve to the same module as the react import from inside the react-dom package.
If these react imports resolve to two different exports objects, you will see this warning. This may happen if you accidentally end up with two copies of the react package.
[...]
If you see more than one React, you’ll need to figure out why this happens and fix your dependency tree. For example, maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency). Until that library is fixed, Yarn resolutions is one possible workaround.

Found more info at this open issue for React: https://github.com/facebook/react/issues/13991

I verified that the react-components used a different instance of React with the method listed in docs, linked earler:

```
// Add this in node_modules/react-dom/index.js
window.React1 = require('react');

// Add this in your component file 
// (in this case e.g. node_modules/@sebgroup/react-components/dist/CheckBox)
require('react-dom');
window.React2 = require('react');
console.log(window.React1 === window.React2);
```

More info regarding dependencies in this SO post: http://stackoverflow.com/questions/30451556/ddg#30454133

Other possible dependencies that should be peer/dev dependency (used for docs?):

- `react-router`
- `react-router-dom`
- `react-dom`

**Comment by aurelius0523** [comment]
Also come across the same issue. Currently bypassing this by making webpack refer to only one instance of react following this. https://github.com/facebook/react/issues/13991#issuecomment-435587809.

That's just a workaround and what @nileke suggested should be done. Similar approach was taken by [Material UI](https://github.com/mui-org/material-ui/blob/master/package.json)

**Comment by yousifalraheem** [comment]
I'm not sure if this issue have been resolved for you guys, I hope you update me on the matter.

`react` is listed as a dependency because it is a core dependency for the [documentation](https://sebgroup.github.io/react-components/#/about). However, we are defining `react` as an external dependency in [webpack.config.prod.js](https://github.com/sebgroup/react-components/blob/develop/webpack.config.build.js) file. Meaning that `react` will not be bundled, instead, it will be treated as a peer dependency.

it will be listed under `react-components` marked with `deduped` because `npm` knows that the package depends on it, but you won't find it inside the `node_modules` folder of the package. The reason why you might be having this issue is because of using an old version of `react` or something else. It would be helpful if you can provide further information.

![Screenshot 2020-01-15 at 14 53 22](https://user-images.githubusercontent.com/10633734/72411820-c9534d80-37a6-11ea-93d0-9363b5fbdb20.png)

If the issue is not resolved yet please follow these steps:
1. comment out all the places where you use our components
2. start uncommenting them one by one and saving each time to see if the error occurs
3. when you find which component is causing the issue please post a snippet of how it's being used so we can replicate the incident

**Comment by aurelius0523** [comment]
Though I'm cannot be 100% certain this is the reason why, do you think it's possible side effect of upgrading from seb component v1 to v2? I notice that team members who start with v2 directly doesn't seem to have this issue.

**Comment by nileke** [comment]
Could be the case. We encountered this during an upgrade in components using hooks and seb components. Also `npm ls react` didn't give the `dedupe` message as it does in @yousifalraheem 's example. 

I cloned our project and bumped the version of sebgroup/react-components before installing and weren't able to reproduce the effect. Here `npm ls react` yields the `dedupe` message for the react dependency. 

Haven't had a look at the change notes for npm or react, but these versions were also bumped since the original post. 

I'll try an upgrade again when we're done with the current work and give an update.
